apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex-cluster-deployment
  labels:
    app: ex-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ex-cluster
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 34%
      maxUnavailable: 34%
  template:
    metadata:
      name: ex-cluster
      labels:
        app: ex-cluster
    spec:
      containers:
      - name: ex-cluster
        image: ex_cluster:local
        imagePullPolicy: Never
        env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_COOKIE
              value: "cookie"
